spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: mooner510
    password: mooner510
    driver-class-name: com.mysql.cj.jdbc.Driver